version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
      - 'automerge'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
