version = 1

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[merge]
method = "rebase"

[merge.message]
title = "pull_request_title"
include_coauthors = true
include_pull_request_author = true

[approve]
auto_approve_usernames = ["dependabot"]
