name: Deploy GitHub Pages

on:
  push:
    branches: [main, docs]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd documentation
          yarn install --frozen-lockfile
      - name: Build
        run: |
          cd documentation
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: documentation/build
